package entities;
// Generated May 4, 2018 2:14:44 PM by Hibernate Tools 4.3.1



/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private int articleId;
     private String articleTitle;
     private String articleContent;
     private String articleCreateDay;
     private String articlePostDay;
     private String articleSource;

    public Article() {
    }

	
    public Article(int articleId) {
        this.articleId = articleId;
    }
    public Article(int articleId, String articleTitle, String articleContent, String articleCreateDay, String articlePostDay, String articleSource) {
       this.articleId = articleId;
       this.articleTitle = articleTitle;
       this.articleContent = articleContent;
       this.articleCreateDay = articleCreateDay;
       this.articlePostDay = articlePostDay;
       this.articleSource = articleSource;
    }
   
    public int getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }
    public String getArticleTitle() {
        return this.articleTitle;
    }
    
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }
    public String getArticleContent() {
        return this.articleContent;
    }
    
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }
    public String getArticleCreateDay() {
        return this.articleCreateDay;
    }
    
    public void setArticleCreateDay(String articleCreateDay) {
        this.articleCreateDay = articleCreateDay;
    }
    public String getArticlePostDay() {
        return this.articlePostDay;
    }
    
    public void setArticlePostDay(String articlePostDay) {
        this.articlePostDay = articlePostDay;
    }
    public String getArticleSource() {
        return this.articleSource;
    }
    
    public void setArticleSource(String articleSource) {
        this.articleSource = articleSource;
    }




}


