package entities;
// Generated May 4, 2018 2:14:44 PM by Hibernate Tools 4.3.1



/**
 * Dishes generated by hbm2java
 */
public class Dishes  implements java.io.Serializable {


     private int dishId;
     private int foodId;
     private String dishName;
     private Integer dishEnergy;
     private String dishRecipe;
     private String dishIngredient;
     private String water;
     private String energy;
     private String protein;
     private String lipid;
     private String carbohydrate;
     private String celluloza;
     private String tro;
     private String totalSugar;
     private String galactoza;
     private String maltoza;
     private String lactoza;
     private String fructoza;
     private String glucoza;
     private String sacaroza;
     private String calcium;
     private String iron;
     private String magnesium;
     private String manganese;
     private String phosphorous;
     private String potassium;
     private String sodium;
     private String zinc;
     private String copper;
     private String selenium;
     private String vitaminC;
     private String vitaminB1;
     private String vitaminB2;
     private String vitaminPp;
     private String vitaminB5;
     private String vitaminB6;
     private String folat;
     private String vitaminB9;
     private String vitaminH;
     private String vitaminB12;
     private String vitaminA;
     private String vitaminD;
     private String vitaminE;
     private String vitaminK;
     private String betaCaroten;
     private String alphaCaroten;
     private String betaCryptoxanthin;
     private String lycopen;
     private String lutein;
     private String purin;
     private String totalIsoflavone;
     private String daidzein;
     private String genistein;
     private String glycetin;
     private String totalSFAcid;
     private String palmitic;
     private String margaric;
     private String stearic;
     private String arachidic;
     private String behenic;
     private String lignoceric;
     private String totalMFAcid;
     private String myristoleic;
     private String palmitoleic;
     private String oleic;
     private String totalPFAcid;
     private String linoleic;
     private String linolenic;
     private String arachidonic;
     private String eicosapentaenoic;
     private String docosahexaenoic;
     private String totalTFAcid;
     private String cholesterol;
     private String phytosterol;
     private String lysin;
     private String methionin;
     private String tryptophan;
     private String phenylalanin;
     private String threonin;
     private String valin;
     private String leucin;
     private String isoleucin;
     private String arginin;
     private String histidin;
     private String cystin;
     private String tyrosin;
     private String alanin;
     private String acidAspartic;
     private String acidGlutamic;
     private String glycin;
     private String prolin;
     private String serin;

    public Dishes() {
    }

	
    public Dishes(int dishId, int foodId) {
        this.dishId = dishId;
        this.foodId = foodId;
    }
    public Dishes(int dishId, int foodId, String dishName, Integer dishEnergy, String dishRecipe, String dishIngredient, String water, String energy, String protein, String lipid, String carbohydrate, String celluloza, String tro, String totalSugar, String galactoza, String maltoza, String lactoza, String fructoza, String glucoza, String sacaroza, String calcium, String iron, String magnesium, String manganese, String phosphorous, String potassium, String sodium, String zinc, String copper, String selenium, String vitaminC, String vitaminB1, String vitaminB2, String vitaminPp, String vitaminB5, String vitaminB6, String folat, String vitaminB9, String vitaminH, String vitaminB12, String vitaminA, String vitaminD, String vitaminE, String vitaminK, String betaCaroten, String alphaCaroten, String betaCryptoxanthin, String lycopen, String lutein, String purin, String totalIsoflavone, String daidzein, String genistein, String glycetin, String totalSFAcid, String palmitic, String margaric, String stearic, String arachidic, String behenic, String lignoceric, String totalMFAcid, String myristoleic, String palmitoleic, String oleic, String totalPFAcid, String linoleic, String linolenic, String arachidonic, String eicosapentaenoic, String docosahexaenoic, String totalTFAcid, String cholesterol, String phytosterol, String lysin, String methionin, String tryptophan, String phenylalanin, String threonin, String valin, String leucin, String isoleucin, String arginin, String histidin, String cystin, String tyrosin, String alanin, String acidAspartic, String acidGlutamic, String glycin, String prolin, String serin) {
       this.dishId = dishId;
       this.foodId = foodId;
       this.dishName = dishName;
       this.dishEnergy = dishEnergy;
       this.dishRecipe = dishRecipe;
       this.dishIngredient = dishIngredient;
       this.water = water;
       this.energy = energy;
       this.protein = protein;
       this.lipid = lipid;
       this.carbohydrate = carbohydrate;
       this.celluloza = celluloza;
       this.tro = tro;
       this.totalSugar = totalSugar;
       this.galactoza = galactoza;
       this.maltoza = maltoza;
       this.lactoza = lactoza;
       this.fructoza = fructoza;
       this.glucoza = glucoza;
       this.sacaroza = sacaroza;
       this.calcium = calcium;
       this.iron = iron;
       this.magnesium = magnesium;
       this.manganese = manganese;
       this.phosphorous = phosphorous;
       this.potassium = potassium;
       this.sodium = sodium;
       this.zinc = zinc;
       this.copper = copper;
       this.selenium = selenium;
       this.vitaminC = vitaminC;
       this.vitaminB1 = vitaminB1;
       this.vitaminB2 = vitaminB2;
       this.vitaminPp = vitaminPp;
       this.vitaminB5 = vitaminB5;
       this.vitaminB6 = vitaminB6;
       this.folat = folat;
       this.vitaminB9 = vitaminB9;
       this.vitaminH = vitaminH;
       this.vitaminB12 = vitaminB12;
       this.vitaminA = vitaminA;
       this.vitaminD = vitaminD;
       this.vitaminE = vitaminE;
       this.vitaminK = vitaminK;
       this.betaCaroten = betaCaroten;
       this.alphaCaroten = alphaCaroten;
       this.betaCryptoxanthin = betaCryptoxanthin;
       this.lycopen = lycopen;
       this.lutein = lutein;
       this.purin = purin;
       this.totalIsoflavone = totalIsoflavone;
       this.daidzein = daidzein;
       this.genistein = genistein;
       this.glycetin = glycetin;
       this.totalSFAcid = totalSFAcid;
       this.palmitic = palmitic;
       this.margaric = margaric;
       this.stearic = stearic;
       this.arachidic = arachidic;
       this.behenic = behenic;
       this.lignoceric = lignoceric;
       this.totalMFAcid = totalMFAcid;
       this.myristoleic = myristoleic;
       this.palmitoleic = palmitoleic;
       this.oleic = oleic;
       this.totalPFAcid = totalPFAcid;
       this.linoleic = linoleic;
       this.linolenic = linolenic;
       this.arachidonic = arachidonic;
       this.eicosapentaenoic = eicosapentaenoic;
       this.docosahexaenoic = docosahexaenoic;
       this.totalTFAcid = totalTFAcid;
       this.cholesterol = cholesterol;
       this.phytosterol = phytosterol;
       this.lysin = lysin;
       this.methionin = methionin;
       this.tryptophan = tryptophan;
       this.phenylalanin = phenylalanin;
       this.threonin = threonin;
       this.valin = valin;
       this.leucin = leucin;
       this.isoleucin = isoleucin;
       this.arginin = arginin;
       this.histidin = histidin;
       this.cystin = cystin;
       this.tyrosin = tyrosin;
       this.alanin = alanin;
       this.acidAspartic = acidAspartic;
       this.acidGlutamic = acidGlutamic;
       this.glycin = glycin;
       this.prolin = prolin;
       this.serin = serin;
    }
   
    public int getDishId() {
        return this.dishId;
    }
    
    public void setDishId(int dishId) {
        this.dishId = dishId;
    }
    public int getFoodId() {
        return this.foodId;
    }
    
    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }
    public String getDishName() {
        return this.dishName;
    }
    
    public void setDishName(String dishName) {
        this.dishName = dishName;
    }
    public Integer getDishEnergy() {
        return this.dishEnergy;
    }
    
    public void setDishEnergy(Integer dishEnergy) {
        this.dishEnergy = dishEnergy;
    }
    public String getDishRecipe() {
        return this.dishRecipe;
    }
    
    public void setDishRecipe(String dishRecipe) {
        this.dishRecipe = dishRecipe;
    }
    public String getDishIngredient() {
        return this.dishIngredient;
    }
    
    public void setDishIngredient(String dishIngredient) {
        this.dishIngredient = dishIngredient;
    }
    public String getWater() {
        return this.water;
    }
    
    public void setWater(String water) {
        this.water = water;
    }
    public String getEnergy() {
        return this.energy;
    }
    
    public void setEnergy(String energy) {
        this.energy = energy;
    }
    public String getProtein() {
        return this.protein;
    }
    
    public void setProtein(String protein) {
        this.protein = protein;
    }
    public String getLipid() {
        return this.lipid;
    }
    
    public void setLipid(String lipid) {
        this.lipid = lipid;
    }
    public String getCarbohydrate() {
        return this.carbohydrate;
    }
    
    public void setCarbohydrate(String carbohydrate) {
        this.carbohydrate = carbohydrate;
    }
    public String getCelluloza() {
        return this.celluloza;
    }
    
    public void setCelluloza(String celluloza) {
        this.celluloza = celluloza;
    }
    public String getTro() {
        return this.tro;
    }
    
    public void setTro(String tro) {
        this.tro = tro;
    }
    public String getTotalSugar() {
        return this.totalSugar;
    }
    
    public void setTotalSugar(String totalSugar) {
        this.totalSugar = totalSugar;
    }
    public String getGalactoza() {
        return this.galactoza;
    }
    
    public void setGalactoza(String galactoza) {
        this.galactoza = galactoza;
    }
    public String getMaltoza() {
        return this.maltoza;
    }
    
    public void setMaltoza(String maltoza) {
        this.maltoza = maltoza;
    }
    public String getLactoza() {
        return this.lactoza;
    }
    
    public void setLactoza(String lactoza) {
        this.lactoza = lactoza;
    }
    public String getFructoza() {
        return this.fructoza;
    }
    
    public void setFructoza(String fructoza) {
        this.fructoza = fructoza;
    }
    public String getGlucoza() {
        return this.glucoza;
    }
    
    public void setGlucoza(String glucoza) {
        this.glucoza = glucoza;
    }
    public String getSacaroza() {
        return this.sacaroza;
    }
    
    public void setSacaroza(String sacaroza) {
        this.sacaroza = sacaroza;
    }
    public String getCalcium() {
        return this.calcium;
    }
    
    public void setCalcium(String calcium) {
        this.calcium = calcium;
    }
    public String getIron() {
        return this.iron;
    }
    
    public void setIron(String iron) {
        this.iron = iron;
    }
    public String getMagnesium() {
        return this.magnesium;
    }
    
    public void setMagnesium(String magnesium) {
        this.magnesium = magnesium;
    }
    public String getManganese() {
        return this.manganese;
    }
    
    public void setManganese(String manganese) {
        this.manganese = manganese;
    }
    public String getPhosphorous() {
        return this.phosphorous;
    }
    
    public void setPhosphorous(String phosphorous) {
        this.phosphorous = phosphorous;
    }
    public String getPotassium() {
        return this.potassium;
    }
    
    public void setPotassium(String potassium) {
        this.potassium = potassium;
    }
    public String getSodium() {
        return this.sodium;
    }
    
    public void setSodium(String sodium) {
        this.sodium = sodium;
    }
    public String getZinc() {
        return this.zinc;
    }
    
    public void setZinc(String zinc) {
        this.zinc = zinc;
    }
    public String getCopper() {
        return this.copper;
    }
    
    public void setCopper(String copper) {
        this.copper = copper;
    }
    public String getSelenium() {
        return this.selenium;
    }
    
    public void setSelenium(String selenium) {
        this.selenium = selenium;
    }
    public String getVitaminC() {
        return this.vitaminC;
    }
    
    public void setVitaminC(String vitaminC) {
        this.vitaminC = vitaminC;
    }
    public String getVitaminB1() {
        return this.vitaminB1;
    }
    
    public void setVitaminB1(String vitaminB1) {
        this.vitaminB1 = vitaminB1;
    }
    public String getVitaminB2() {
        return this.vitaminB2;
    }
    
    public void setVitaminB2(String vitaminB2) {
        this.vitaminB2 = vitaminB2;
    }
    public String getVitaminPp() {
        return this.vitaminPp;
    }
    
    public void setVitaminPp(String vitaminPp) {
        this.vitaminPp = vitaminPp;
    }
    public String getVitaminB5() {
        return this.vitaminB5;
    }
    
    public void setVitaminB5(String vitaminB5) {
        this.vitaminB5 = vitaminB5;
    }
    public String getVitaminB6() {
        return this.vitaminB6;
    }
    
    public void setVitaminB6(String vitaminB6) {
        this.vitaminB6 = vitaminB6;
    }
    public String getFolat() {
        return this.folat;
    }
    
    public void setFolat(String folat) {
        this.folat = folat;
    }
    public String getVitaminB9() {
        return this.vitaminB9;
    }
    
    public void setVitaminB9(String vitaminB9) {
        this.vitaminB9 = vitaminB9;
    }
    public String getVitaminH() {
        return this.vitaminH;
    }
    
    public void setVitaminH(String vitaminH) {
        this.vitaminH = vitaminH;
    }
    public String getVitaminB12() {
        return this.vitaminB12;
    }
    
    public void setVitaminB12(String vitaminB12) {
        this.vitaminB12 = vitaminB12;
    }
    public String getVitaminA() {
        return this.vitaminA;
    }
    
    public void setVitaminA(String vitaminA) {
        this.vitaminA = vitaminA;
    }
    public String getVitaminD() {
        return this.vitaminD;
    }
    
    public void setVitaminD(String vitaminD) {
        this.vitaminD = vitaminD;
    }
    public String getVitaminE() {
        return this.vitaminE;
    }
    
    public void setVitaminE(String vitaminE) {
        this.vitaminE = vitaminE;
    }
    public String getVitaminK() {
        return this.vitaminK;
    }
    
    public void setVitaminK(String vitaminK) {
        this.vitaminK = vitaminK;
    }
    public String getBetaCaroten() {
        return this.betaCaroten;
    }
    
    public void setBetaCaroten(String betaCaroten) {
        this.betaCaroten = betaCaroten;
    }
    public String getAlphaCaroten() {
        return this.alphaCaroten;
    }
    
    public void setAlphaCaroten(String alphaCaroten) {
        this.alphaCaroten = alphaCaroten;
    }
    public String getBetaCryptoxanthin() {
        return this.betaCryptoxanthin;
    }
    
    public void setBetaCryptoxanthin(String betaCryptoxanthin) {
        this.betaCryptoxanthin = betaCryptoxanthin;
    }
    public String getLycopen() {
        return this.lycopen;
    }
    
    public void setLycopen(String lycopen) {
        this.lycopen = lycopen;
    }
    public String getLutein() {
        return this.lutein;
    }
    
    public void setLutein(String lutein) {
        this.lutein = lutein;
    }
    public String getPurin() {
        return this.purin;
    }
    
    public void setPurin(String purin) {
        this.purin = purin;
    }
    public String getTotalIsoflavone() {
        return this.totalIsoflavone;
    }
    
    public void setTotalIsoflavone(String totalIsoflavone) {
        this.totalIsoflavone = totalIsoflavone;
    }
    public String getDaidzein() {
        return this.daidzein;
    }
    
    public void setDaidzein(String daidzein) {
        this.daidzein = daidzein;
    }
    public String getGenistein() {
        return this.genistein;
    }
    
    public void setGenistein(String genistein) {
        this.genistein = genistein;
    }
    public String getGlycetin() {
        return this.glycetin;
    }
    
    public void setGlycetin(String glycetin) {
        this.glycetin = glycetin;
    }
    public String getTotalSFAcid() {
        return this.totalSFAcid;
    }
    
    public void setTotalSFAcid(String totalSFAcid) {
        this.totalSFAcid = totalSFAcid;
    }
    public String getPalmitic() {
        return this.palmitic;
    }
    
    public void setPalmitic(String palmitic) {
        this.palmitic = palmitic;
    }
    public String getMargaric() {
        return this.margaric;
    }
    
    public void setMargaric(String margaric) {
        this.margaric = margaric;
    }
    public String getStearic() {
        return this.stearic;
    }
    
    public void setStearic(String stearic) {
        this.stearic = stearic;
    }
    public String getArachidic() {
        return this.arachidic;
    }
    
    public void setArachidic(String arachidic) {
        this.arachidic = arachidic;
    }
    public String getBehenic() {
        return this.behenic;
    }
    
    public void setBehenic(String behenic) {
        this.behenic = behenic;
    }
    public String getLignoceric() {
        return this.lignoceric;
    }
    
    public void setLignoceric(String lignoceric) {
        this.lignoceric = lignoceric;
    }
    public String getTotalMFAcid() {
        return this.totalMFAcid;
    }
    
    public void setTotalMFAcid(String totalMFAcid) {
        this.totalMFAcid = totalMFAcid;
    }
    public String getMyristoleic() {
        return this.myristoleic;
    }
    
    public void setMyristoleic(String myristoleic) {
        this.myristoleic = myristoleic;
    }
    public String getPalmitoleic() {
        return this.palmitoleic;
    }
    
    public void setPalmitoleic(String palmitoleic) {
        this.palmitoleic = palmitoleic;
    }
    public String getOleic() {
        return this.oleic;
    }
    
    public void setOleic(String oleic) {
        this.oleic = oleic;
    }
    public String getTotalPFAcid() {
        return this.totalPFAcid;
    }
    
    public void setTotalPFAcid(String totalPFAcid) {
        this.totalPFAcid = totalPFAcid;
    }
    public String getLinoleic() {
        return this.linoleic;
    }
    
    public void setLinoleic(String linoleic) {
        this.linoleic = linoleic;
    }
    public String getLinolenic() {
        return this.linolenic;
    }
    
    public void setLinolenic(String linolenic) {
        this.linolenic = linolenic;
    }
    public String getArachidonic() {
        return this.arachidonic;
    }
    
    public void setArachidonic(String arachidonic) {
        this.arachidonic = arachidonic;
    }
    public String getEicosapentaenoic() {
        return this.eicosapentaenoic;
    }
    
    public void setEicosapentaenoic(String eicosapentaenoic) {
        this.eicosapentaenoic = eicosapentaenoic;
    }
    public String getDocosahexaenoic() {
        return this.docosahexaenoic;
    }
    
    public void setDocosahexaenoic(String docosahexaenoic) {
        this.docosahexaenoic = docosahexaenoic;
    }
    public String getTotalTFAcid() {
        return this.totalTFAcid;
    }
    
    public void setTotalTFAcid(String totalTFAcid) {
        this.totalTFAcid = totalTFAcid;
    }
    public String getCholesterol() {
        return this.cholesterol;
    }
    
    public void setCholesterol(String cholesterol) {
        this.cholesterol = cholesterol;
    }
    public String getPhytosterol() {
        return this.phytosterol;
    }
    
    public void setPhytosterol(String phytosterol) {
        this.phytosterol = phytosterol;
    }
    public String getLysin() {
        return this.lysin;
    }
    
    public void setLysin(String lysin) {
        this.lysin = lysin;
    }
    public String getMethionin() {
        return this.methionin;
    }
    
    public void setMethionin(String methionin) {
        this.methionin = methionin;
    }
    public String getTryptophan() {
        return this.tryptophan;
    }
    
    public void setTryptophan(String tryptophan) {
        this.tryptophan = tryptophan;
    }
    public String getPhenylalanin() {
        return this.phenylalanin;
    }
    
    public void setPhenylalanin(String phenylalanin) {
        this.phenylalanin = phenylalanin;
    }
    public String getThreonin() {
        return this.threonin;
    }
    
    public void setThreonin(String threonin) {
        this.threonin = threonin;
    }
    public String getValin() {
        return this.valin;
    }
    
    public void setValin(String valin) {
        this.valin = valin;
    }
    public String getLeucin() {
        return this.leucin;
    }
    
    public void setLeucin(String leucin) {
        this.leucin = leucin;
    }
    public String getIsoleucin() {
        return this.isoleucin;
    }
    
    public void setIsoleucin(String isoleucin) {
        this.isoleucin = isoleucin;
    }
    public String getArginin() {
        return this.arginin;
    }
    
    public void setArginin(String arginin) {
        this.arginin = arginin;
    }
    public String getHistidin() {
        return this.histidin;
    }
    
    public void setHistidin(String histidin) {
        this.histidin = histidin;
    }
    public String getCystin() {
        return this.cystin;
    }
    
    public void setCystin(String cystin) {
        this.cystin = cystin;
    }
    public String getTyrosin() {
        return this.tyrosin;
    }
    
    public void setTyrosin(String tyrosin) {
        this.tyrosin = tyrosin;
    }
    public String getAlanin() {
        return this.alanin;
    }
    
    public void setAlanin(String alanin) {
        this.alanin = alanin;
    }
    public String getAcidAspartic() {
        return this.acidAspartic;
    }
    
    public void setAcidAspartic(String acidAspartic) {
        this.acidAspartic = acidAspartic;
    }
    public String getAcidGlutamic() {
        return this.acidGlutamic;
    }
    
    public void setAcidGlutamic(String acidGlutamic) {
        this.acidGlutamic = acidGlutamic;
    }
    public String getGlycin() {
        return this.glycin;
    }
    
    public void setGlycin(String glycin) {
        this.glycin = glycin;
    }
    public String getProlin() {
        return this.prolin;
    }
    
    public void setProlin(String prolin) {
        this.prolin = prolin;
    }
    public String getSerin() {
        return this.serin;
    }
    
    public void setSerin(String serin) {
        this.serin = serin;
    }




}


