package entities;
// Generated May 4, 2018 2:14:44 PM by Hibernate Tools 4.3.1



/**
 * FoodCategory generated by hbm2java
 */
public class FoodCategory  implements java.io.Serializable {


     private int foodCategoryId;
     private String foodCategoryName;

    public FoodCategory() {
    }

	
    public FoodCategory(int foodCategoryId) {
        this.foodCategoryId = foodCategoryId;
    }
    public FoodCategory(int foodCategoryId, String foodCategoryName) {
       this.foodCategoryId = foodCategoryId;
       this.foodCategoryName = foodCategoryName;
    }
   
    public int getFoodCategoryId() {
        return this.foodCategoryId;
    }
    
    public void setFoodCategoryId(int foodCategoryId) {
        this.foodCategoryId = foodCategoryId;
    }
    public String getFoodCategoryName() {
        return this.foodCategoryName;
    }
    
    public void setFoodCategoryName(String foodCategoryName) {
        this.foodCategoryName = foodCategoryName;
    }




}


