package entities;
// Generated May 4, 2018 2:14:44 PM by Hibernate Tools 4.3.1



/**
 * MemberAccount generated by hbm2java
 */
public class MemberAccount  implements java.io.Serializable {


     private int memberId;
     private String memberLoginName;
     private String memberPassword;
     private String memberGender;
     private String memberAddress;
     private String memberPhoneNumber;
     private String memberGoal;
     private Integer memberHeight;
     private Integer memberWeight;
     private String memberPreferrence;
     private String memberActiveLevel;

    public MemberAccount() {
    }

	
    public MemberAccount(int memberId, String memberLoginName, String memberPassword) {
        this.memberId = memberId;
        this.memberLoginName = memberLoginName;
        this.memberPassword = memberPassword;
    }
    public MemberAccount(int memberId, String memberLoginName, String memberPassword, String memberGender, String memberAddress, String memberPhoneNumber, String memberGoal, Integer memberHeight, Integer memberWeight, String memberPreferrence, String memberActiveLevel) {
       this.memberId = memberId;
       this.memberLoginName = memberLoginName;
       this.memberPassword = memberPassword;
       this.memberGender = memberGender;
       this.memberAddress = memberAddress;
       this.memberPhoneNumber = memberPhoneNumber;
       this.memberGoal = memberGoal;
       this.memberHeight = memberHeight;
       this.memberWeight = memberWeight;
       this.memberPreferrence = memberPreferrence;
       this.memberActiveLevel = memberActiveLevel;
    }
   
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }
    public String getMemberLoginName() {
        return this.memberLoginName;
    }
    
    public void setMemberLoginName(String memberLoginName) {
        this.memberLoginName = memberLoginName;
    }
    public String getMemberPassword() {
        return this.memberPassword;
    }
    
    public void setMemberPassword(String memberPassword) {
        this.memberPassword = memberPassword;
    }
    public String getMemberGender() {
        return this.memberGender;
    }
    
    public void setMemberGender(String memberGender) {
        this.memberGender = memberGender;
    }
    public String getMemberAddress() {
        return this.memberAddress;
    }
    
    public void setMemberAddress(String memberAddress) {
        this.memberAddress = memberAddress;
    }
    public String getMemberPhoneNumber() {
        return this.memberPhoneNumber;
    }
    
    public void setMemberPhoneNumber(String memberPhoneNumber) {
        this.memberPhoneNumber = memberPhoneNumber;
    }
    public String getMemberGoal() {
        return this.memberGoal;
    }
    
    public void setMemberGoal(String memberGoal) {
        this.memberGoal = memberGoal;
    }
    public Integer getMemberHeight() {
        return this.memberHeight;
    }
    
    public void setMemberHeight(Integer memberHeight) {
        this.memberHeight = memberHeight;
    }
    public Integer getMemberWeight() {
        return this.memberWeight;
    }
    
    public void setMemberWeight(Integer memberWeight) {
        this.memberWeight = memberWeight;
    }
    public String getMemberPreferrence() {
        return this.memberPreferrence;
    }
    
    public void setMemberPreferrence(String memberPreferrence) {
        this.memberPreferrence = memberPreferrence;
    }
    public String getMemberActiveLevel() {
        return this.memberActiveLevel;
    }
    
    public void setMemberActiveLevel(String memberActiveLevel) {
        this.memberActiveLevel = memberActiveLevel;
    }




}


